### ISSUE TITLE
docker compose exec does not work

### ISSUE THREAD

**Issue by electfreak** [kochaika/simulavr-docker#1]
I've followed the guide.

after command `docker compose -f docker-compose.yml -p simulavr up -d` I ran `docker compose exec simulavr /bin/bash` and got `service "simulavr" is not running container #1`.

Docker version 20.10.22, build 3a2c30b

**Comment by kochaika** [comment]
Are you sure container is started successfully?
Maybe container have different name...
run `docker ps -a` after docker compose up` command to ensure

**Comment by kochaika** [comment]
Use `docker compose -p simulavr exec simulavr /bin/bash`
I will update readme, thank you!
